# Generated by Django 4.2.7 on 2023-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('task', models.TextField()),
                ('date', models.DateField()),
                ('progres', models.CharField(max_length=50)),
            ],
        ),
    ]
