# Generated by Django 4.2.7 on 2023-11-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reja',
            old_name='progres',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='reja',
            old_name='task',
            new_name='t_detail',
        ),
        migrations.RenameField(
            model_name='reja',
            old_name='name',
            new_name='t_name',
        ),
    ]
